{{- $ingress := .Values.ingress | default dict -}}
{{- $service := .Values.service | default dict -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "order-service.fullname" . }}
spec:
  ingressClassName: {{ $ingress.ingressClassName | quote }}
  rules:
    - host: {{ $ingress.hostname }}
      http:
        paths:
          {{- if $ingress.extraPaths }}
          {{- toYaml $ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path : {{ $ingress.path }}
            pathType: {{ $ingress.pathType }}
            backend:
              service:
                name: {{ include "order-service.fullname" . }}
                port:
                  number: {{ $service.port }}
{{- end }}