{{- if (include "order-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "order-service.fullname" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9b3JkZXJzZXJ2aWNlZGI7VXNlciBJRD1vcmRlcnNlcnZpY2U7cGFzc3dvcmQ9cGFzc3dvcmQ7
  KafkaConsumer__Password: ZmZWVUZwTW54WQ==
  KafkaProducer__Password: ZmZWVUZwTW54WQ==
{{- end }}