{{- if (include "order-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  order-service-secret-db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9T3JkZXJTZXJ2aWNlRGI7VXNlciBJRD1vcmRlcnNlcnZpY2U7cGFzc3dvcmQ9cGFzc3dvcmQ7
{{- end }}