{{- if (include "payment-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "payment-service.fullname" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9cGF5bWVudHNlcnZpY2VkYjtVc2VyIElEPXBheW1lbnRzZXJ2aWNlO3Bhc3N3b3JkPXBhc3N3b3JkOw==
  KafkaProducer__Password: ZmZWVUZwTW54WQ==
{{- end }}