{{- if (include "auth-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  auth-service-secret-db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9YXV0aHNlcnZpY2VkYjtVc2VyIElEPWF1dGhzZXJ2aWNlO3Bhc3N3b3JkPXBhc3N3b3JkOw==
{{- end }}