{{- if (include "auth-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "auth-service.fullname" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9YXV0aHNlcnZpY2VkYjtVc2VyIElEPWF1dGhzZXJ2aWNlO3Bhc3N3b3JkPXBhc3N3b3JkOw==
  KafkaProducer__Password: ZmZWVUZwTW54WQ==
{{- end }}