{{- if (include "product-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "product-service.fullname" . }}
type: Opaque
data:
  MONGODBURI: bW9uZ29kYjovL3Byb2R1Y3Qtc2VydmljZTpwYXNzd29yZEBtb25nb2RiOjI3MDE3L3Byb2R1Y3Qtc2VydmljZQ==
{{- end }}