{{- if (include "delivery-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "delivery-service.fullname" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9ZGVsaXZlcnlzZXJ2aWNlZGI7VXNlciBJRD1kZWxpdmVyeXNlcnZpY2U7cGFzc3dvcmQ9cGFzc3dvcmQ7
{{- end }}