{{- if (include "user-service.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
    name:  {{ include "user-service.fullname" . }}
data:
    IdentityServerClient__Authority: "http://auth-service"
    IdentityServerClient__Audience: "user-service"
    KafkaConsumer__BootstrapServers: "kafka.default.svc.cluster.local:9092"
 {{- end }}