{{- if (include "user-service.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
    name:  {{ include "user-service.fullname" . }}
data:
    IdentityServerClient__Authority: "auth-service"
    IdentityServerClient__Audience: "otus"
 {{- end }}