{{- if (include "notification-service.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
    name:  {{ include "notification-service.fullname" . }}
data:
    IdentityServerClient__Authority: "http://auth-service"
    IdentityServerClient__Audience: "otus"
    KafkaConsumer__BootstrapServers: "kafka.default.svc.cluster.local:9092"
 {{- end }}