{{- if (include "notification-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "notification-service.fullname" . }}
type: Opaque
data:
  MONGODBURI: bW9uZ29kYjovL25vdGlmaWNhdGlvbi1zZXJ2aWNlOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvbm90aWZpY2F0aW9uLXNlcnZpY2U=
  KafkaConsumer__Password: ZmZWVUZwTW54WQ==
{{- end }}