{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ include "notification-service.fullname" . }}
spec: 
    endpoints:
        - port: {{ .Values.service.name }}
          scrapeTimeout: 30s
          path: /metrics
          scheme: http
    namespaceSelector:
        matchNames:
            - default
    selector: 
        matchLabels: 
            app: {{ include "notification-service.name" . }}
{{- end }}