{{- if (include "stock-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "stock-service.fullname" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9c3RvY2tzZXJ2aWNlZGI7VXNlciBJRD1zdG9ja3NlcnZpY2U7cGFzc3dvcmQ9cGFzc3dvcmQ7
{{- end }}