{{- $service := .Values.service | default dict -}}
apiVersion: v1
kind: Service
metadata: 
  name: {{ include "stock-service.fullname" . }}
  labels: 
    app: {{ include "stock-service.name" . }}
spec:
  selector: 
    app: {{ include "stock-service.name" . }}
  ports:
    - protocol: {{ $service.protocol }}
      port: {{ $service.port }}
      targetPort: {{ .Values.containerPort }}
      name: {{ $service.name }}
  type: {{ $service.type }}